Streamline window and dialog styles
telerik/kendo-theme-default pull request #227
Opened 2017-02-20 13:56 UTC by joneff

2017-02-20 14:03 UTC, joneff commented on scss/_variables.scss
> +$font-size-lg: 19px !default;
Used correct font size according to design

2017-02-20 14:03 UTC, joneff commented on scss/_variables.scss
> +$window-titlebar-padding-y: 16px !default;
* renamed variables
* use correct values for variables

2017-02-20 14:03 UTC, joneff commented on scss/common/_base.scss
> +
moved `.k-overlay` to `_base.scss`

2017-02-20 14:03 UTC, joneff commented on scss/dialog.scss
> +@import "action-buttons";
improve component dependencies

2017-02-20 14:03 UTC, joneff commented on scss/dialog/_theme.scss
> +    .k-dialog {}
* remove variables
* inherit most of the styles from window

2017-02-20 14:03 UTC, joneff commented on scss/window/_theme.scss
> +            transform: scale(2);
Not necessarily the best solution, but icons don't scale well  when not using factor of 2 e.g. 1.5

2017-02-24 15:24 UTC, gyoshev commented on scss/window/_theme.scss
> +            transform: scale(2);
It's not ideal, to say the least. After a discussion with @yordanov, the close button seems to be a good candidate for a `.k-bare` button, without the scaling.

2017-02-24 15:26 UTC, gyoshev commented
Content layout in IE11 is broken due to the `.k-window-content { flex: 1; }`

![image](https://cloud.githubusercontent.com/assets/90405/23309124/28d98cf0-fab6-11e6-8ff2-a58d3473e5bc.png)

I added `flex: 1 1 auto` in 9f59890, which resolves the problem in Angular. If it's good with the jQuery dialog, it could stay -- otherwise maybe flexbox is not the answer.

2017-02-24 15:27 UTC, gyoshev requested changes
We should address the close button appearance without the scaling.

2017-02-27 17:36 UTC, joneff commented
@gyoshev I confirm. this solves the issue. 770af00 removes the scale-on-hover effect.

2017-02-27 17:54 UTC, joneff commented
@gyoshev even though 55e23d8 removes the styling, the action buttons still need `k-icon-button` class, otherwise dimensions will not be as accurate.

2017-03-01 12:18 UTC, gyoshev approved these changes

2017-03-02 12:01 UTC, merged