fix(switch): displaced switch handle
telerik/kendo-theme-default pull request #273
Opened 2017-03-06 16:38 UTC by inikolova

Closes telerik/kendo-theme-default#226

2017-03-07 09:54 UTC, joneff requested changes
Only the left margin should be changed.

2017-03-07 09:54 UTC, joneff commented on scss/switch/_layout.scss
> +        margin: 0 ($padding-x-lg / 2) 0 ($padding-x-sm / 2);
The left margin should be the same as the top padding of `.k-switch-container`. Perhaps, we could extract it as a new variable e.g. `$switch-padding`.

On a side note, to me it's best to drop the margin altogether and use only the padding on `.k-switch-container`.

2017-03-08 09:27 UTC, inikolova commented on scss/switch/_layout.scss
> +        margin: 0 ($padding-x-lg / 2) 0 ($padding-x-sm / 2);
@joneff , you're right - I will make the needed changes

2017-03-10 15:32 UTC, joneff approved these changes

2017-03-10 15:44 UTC, merged