Fixes/grid row height
telerik/kendo-theme-default pull request #297
Opened 2017-03-13 15:58 UTC by joneff

As discussed with @yordanov, we should keep hardcoded or calculated values for dimensions from layout, unless needed. Such is the case with certain dimensions in the grid, which force larger metrics in Bootstrap.

I've moved those into grid/theme.

2017-03-14 11:47 UTC, inikolova commented
In my opinion, dimensions should be kept in the **_layout** files. When overrides for different themes are needed, we could use variables

2017-03-14 12:36 UTC, inikolova requested changes

2017-03-14 12:36 UTC, inikolova commented on scss/grid/_layout.scss
> -            line-height: button-size();
This line-height is needed. Please check the following issue: 
https://github.com/telerik/kendo-theme-default/issues/284

2017-03-14 13:50 UTC, joneff commented
Fixes https://github.com/telerik/kendo-theme-bootstrap/issues/81

2017-03-14 14:04 UTC, joneff commented on scss/grid/_layout.scss
> -            line-height: button-size();
resolved in 5c96e00

2017-03-14 14:06 UTC, joneff commented
@inikolova I discussed the dimensions with @yordanov. It's easier to set constraints to a said place than to remove them. In terms, the layout is as generic as possible e.g. padding, border-styles etc, and we set restrictions in the theme files.

2017-03-14 14:38 UTC, gyoshev commented
@joneff can you elaborate why the heights are specific to the default theme and not the bootstrap theme? It seems like the filter row and grouping headers should be as high as the buttons and inputs, in any theme, and that the styles will be duplicated unnecessarily in the bootstrap theme.

2017-03-14 14:43 UTC, joneff commented
What's specific for the default theme is that it's needed to have higher filter row and grouping headers than the standard row / header. That's not the case for bootstrap -- rows, headers, filter rows, toolbar etc all have equal height when having one line of content.

On a related note, definitely not the case in Material theme, which has smaller headers, but we'll get to that when we get to that.

2017-03-15 08:53 UTC, gyoshev commented
I confirmed with @yordanov that we don't need a fixed height of the rows for the default theme, as it should adapt to the content of the rows. Rebased and removed the sizing from the theme.

2017-03-15 09:47 UTC, joneff commented
I'm fine with the changes

2017-03-15 12:30 UTC, inikolova approved these changes

2017-03-15 12:32 UTC, merged