fix(grid): expand/collapse icon is not centered
telerik/kendo-theme-default pull request #323
Opened 2017-03-17 17:12 UTC by mvgmvg

fixes https://github.com/telerik/kendo-theme-bootstrap/issues/82

2017-03-20 07:34 UTC, inikolova reviewed
Can we change this hardcoded value 7px? Maybe we could use some calculations? For example (.k-group-col (which is 30px) - $icon-size (16px)) /2? What do you think?

2017-03-20 07:52 UTC, joneff requested changes

2017-03-20 07:52 UTC, joneff commented on scss/grid/_layout.scss
> +            margin-left: addTwo(-1*$cell-padding-x, 7px);
change to 7px to `$icon-spacing / 2`

2017-03-20 08:14 UTC, mvgmvg commented on scss/grid/_layout.scss
> +            margin-left: addTwo(-1*$cell-padding-x, 7px);
I think that there should be used $icon-size variable so icons could be centered in all cases.
If the header [k-group-cell width](https://www.screencast.com/t/TjCqs6jER) is ($icon-size*2), then "7px" can be replaced by ($icon-size/2).

2017-03-21 09:02 UTC, joneff commented on scss/grid/_layout.scss
> +            margin-left: addTwo(-1*$cell-padding-x, 7px);
Agree. You can go ahead with the changes.

2017-03-21 12:53 UTC, joneff approved these changes

2017-03-21 13:18 UTC, merged