Fixes/pickers x icon
telerik/kendo-theme-default pull request #369
Opened 2017-04-05 07:40 UTC by joneff

Fixes position of [x] clear icons in combo, autocomplete and multiselect.

2017-04-19 13:09 UTC, inikolova commented
Clear icon overlaps the text

2017-04-19 13:10 UTC, inikolova commented
Loading indicator is not vertically aligned

2017-04-19 13:12 UTC, magdalenaan reviewed
x-icon in multiselect is upper https://www.screencast.com/t/hBqTTb82F7o

2017-04-19 13:18 UTC, inikolova commented
In MultiSelect for jQuery the **k-i-loading** icon is always visible

2017-04-19 14:16 UTC, inikolova commented
In RTL mode and filtering enabled, the DropDownList appearance is broken

2017-10-23 15:52 UTC, gyoshev requested changes
The code appears to be clearer, however the above comments need to be addressed before merging.

| Before | After |
|-|-|
| ![image](https://user-images.githubusercontent.com/90405/31898388-bc63548c-b821-11e7-8254-8d9621853e13.png) | ![image](https://user-images.githubusercontent.com/90405/31898426-d232f3b2-b821-11e7-9655-6a9c54d35757.png) |
| ![image](https://user-images.githubusercontent.com/90405/31898579-1e739e7a-b822-11e7-956d-1167c55328f8.png) | ![image](https://user-images.githubusercontent.com/90405/31898628-2f6bb8c0-b822-11e7-9f32-d385b6c8f444.png) |
| ![image](https://user-images.githubusercontent.com/90405/31898694-536ba3de-b822-11e7-8b62-6d027f7799d8.png) | ![image](https://user-images.githubusercontent.com/90405/31898720-64937088-b822-11e7-93bb-75e566002ea0.png) |
| ![image](https://user-images.githubusercontent.com/90405/31898814-b2ae06d4-b822-11e7-983b-0aa66ea8453b.png) | ![image](https://user-images.githubusercontent.com/90405/31898771-8e61c0ae-b822-11e7-9d3e-21069948c01a.png) <br> (also gets 100% width) |

Also, the clear button is now always visible in the ComboBox and MultiSelect -- is this by design?

2017-10-24 13:00 UTC, joneff commented on scss/common/_base.scss
> +        border-width: .03125em;
This value should be 0.05 as per https://github.com/telerik/kendo-theme-default/pull/768

2018-02-08 17:43 UTC, gyoshev commented
PR moved to monorepo.

2018-02-08 17:43 UTC, closed without merging