Dropdowns rtl issues and invalid state styling
telerik/kendo-theme-default pull request #501
Opened 2017-05-17 14:14 UTC by inikolova

Related to https://github.com/telerik/kendo-theme-default/issues/493

2017-05-17 15:30 UTC, gyoshev requested changes
Some things we discussed offline:

1. We should remove the rules that mention `&:invalid:not(.ng-valid)`, as these get applied in Kendo UI for jQuery by default, and do not look good
2. The invalid styling can be moved to `common/forms` and get cascaded through `.k-widget.ng-invalid`
3. The `$invalid-border-color` can perhaps be moved to `_variables.scss`.

2017-05-18 10:40 UTC, inikolova commented
The discussed changes has been made

2017-05-18 11:30 UTC, gyoshev approved these changes

2017-05-18 11:50 UTC, joneff approved these changes

2017-05-18 11:50 UTC, joneff commented on scss/common/_forms.scss
> +                color: $error;
if the color is the same, shouldn't `color: inherit` do the same thing?

2017-05-18 12:13 UTC, inikolova commented on scss/common/_forms.scss
> +                color: $error;
@joneff , good catch! I will make this change

2017-05-18 14:00 UTC, merged