fix(dropdowns): misaligned loading indicator; wrong select width
telerik/kendo-theme-default pull request #545
Opened 2017-06-16 14:19 UTC by inikolova

Related to https://github.com/telerik/kendo-theme-default/issues/537

2017-06-20 12:05 UTC, joneff requested changes

2017-06-20 12:05 UTC, joneff commented on scss/common/_forms.scss
> +            right: $padding-x;
shouldn't we combine this selector and the one below?

2017-06-21 15:16 UTC, inikolova commented on scss/common/_forms.scss
> +            right: $padding-x;
@joneff , you're right -> thanks for the tip

2017-06-23 17:38 UTC, joneff approved these changes

2017-06-26 09:03 UTC, merged