fix/tabstrip variable usage
telerik/kendo-theme-default pull request #594
Opened 2017-07-06 18:30 UTC by IanMuirhead

Assigns the selected variable to tabstrip items which are active

@joneff I think there was a bug in the variables which you used for the colors

2017-07-10 10:31 UTC, joneff requested changes

2017-07-10 10:31 UTC, joneff commented on scss/tabstrip/_theme.scss
> +                border-bottom-color: $tabstrip-item-selected-border;
that needs to be `-bg`, as well as the rest of the instances, so we can get the "enclosure" like appearance.

2017-07-18 23:03 UTC, IanMuirhead commented on scss/tabstrip/_theme.scss
> +                border-bottom-color: $tabstrip-item-selected-border;
@joneff Totally missed this response - if it is required to be the 'bg' value here what's the point of having the selected border color?

2017-12-05 16:29 UTC, IanMuirhead commented
Going to close this PR.

I've created a solution locally which resolved our use-cases.

2017-12-05 16:29 UTC, closed without merging